name: motion
dependencies:
  - python=3.10.8
  - pip=22.3.1
  - pip:
      - django==4.1.4
      - djangorestframework==3.14.0
      - djangorestframework-simplejwt==5.2.2
      - pillow==9.3.0
      - drf-yasg==1.21.4